import { ref, readonly } from 'vue'

/**
 * Tiny inventory + fuel store.
 *
 * Shared singleton so the scene, HUD, and crafting menu all agree on state.
 */

const fuel = ref(1)              // 0..1 (full tank)
const ore = ref(0)               // integer count of quarry-ore chunks
const metal = ref(0)             // integer count of smelted metal ingots
// `parts` is the post-meteor electronics salvage (circuit boards, antenna
// fragments, transceivers) recovered from the three broken predecessors.
// Two parts repair the solar cell; one additional part repairs the comms
// module. The crafting menu reads this value alongside `metal`.
const parts = ref(0)
const hasFlagSeen = ref(false)

// Energy is generated by Ewall's rear solar cell. While the cell is
// undamaged we clamp the gauge at 1. Once the cell has been broken by the
// meteor strike, energy drains per metre of forward motion — so the
// player can slow down to stretch reserves but cannot simply wait out the
// clock. At the baseline walk speed of ~3.5 m/s a full tank lasts roughly
// 15 minutes of sustained movement (3.5 m/s * 900 s = 3150 m budget).
const energy = ref(1)
const isSolarCellBroken = ref(false)
const isCommsBroken = ref(false)
/** Metres of walking the full energy bar covers once solar is broken. */
const ENERGY_TRAVEL_BUDGET_METRES = 3150
/** Additional per-second idle drain while solar is broken — small, so
 *  standing still is not a cost-free strategy for ever. */
const ENERGY_IDLE_DRAIN_PER_SEC = 1 / 3600

const addOre = (n = 1) => {
  ore.value += n
}
const consumeOre = (n = 1) => {
  if (ore.value < n) return false
  ore.value -= n
  return true
}
const addMetal = (n = 1) => {
  metal.value += n
}
const consumeMetal = (n = 1) => {
  if (metal.value < n) return false
  metal.value -= n
  return true
}
const addParts = (n = 1) => {
  parts.value += n
}
const consumeParts = (n = 1) => {
  if (parts.value < n) return false
  parts.value -= n
  return true
}

// Flamethrower fuel drain. Calibrated at 0.05/s so a full tank lasts
// ~20 s of sustained firing — 1.6× the previous 0.08/s budget per the
// "tank is 1.6× bigger" tuning note from the user.
const drainFuel = (dt: number, rate = 0.05) => {
  fuel.value = Math.max(0, fuel.value - rate * dt)
}
const refillFuel = () => {
  fuel.value = 1
}
const hasFuel = () => fuel.value > 0.001

/** Tick the energy gauge. While the solar cell is intact the gauge is
 *  pinned at full; once broken, movement distance is the primary drain
 *  (small idle drain on top so stationary survival is finite).
 *  `distanceMoved` is metres in XZ this frame. */
const tickEnergy = (dt: number, distanceMoved = 0) => {
  if (!isSolarCellBroken.value) {
    energy.value = 1
    return
  }
  const moveDrain = distanceMoved / ENERGY_TRAVEL_BUDGET_METRES
  const idleDrain = ENERGY_IDLE_DRAIN_PER_SEC * dt
  energy.value = Math.max(0, energy.value - moveDrain - idleDrain)
}
const breakSolarCell = () => {
  isSolarCellBroken.value = true
}
const repairSolarCell = () => {
  isSolarCellBroken.value = false
  energy.value = 1
}
const breakComms = () => {
  isCommsBroken.value = true
}
const repairComms = () => {
  isCommsBroken.value = false
}

/** Checkpoint snapshot — the post-meteor handoff captures enough inventory
 *  state here that a "continue from last checkpoint" flow can rewind a
 *  Game Over without resetting progress prior to the shower. Scene-level
 *  state (player position, mission phase, salvage flags) lives in the
 *  checkpoint object built by MoonScene and is merged into this store on
 *  restore. */
export interface InventorySnapshot {
  fuel: number
  ore: number
  metal: number
  parts: number
  energy: number
  isSolarCellBroken: boolean
  isCommsBroken: boolean
  hasFlagSeen: boolean
}

const snapshotInventory = (): InventorySnapshot => ({
  fuel: fuel.value,
  ore: ore.value,
  metal: metal.value,
  parts: parts.value,
  energy: energy.value,
  isSolarCellBroken: isSolarCellBroken.value,
  isCommsBroken: isCommsBroken.value,
  hasFlagSeen: hasFlagSeen.value
})

const restoreInventory = (s: InventorySnapshot) => {
  fuel.value = s.fuel
  ore.value = s.ore
  metal.value = s.metal
  parts.value = s.parts
  energy.value = s.energy
  isSolarCellBroken.value = s.isSolarCellBroken
  isCommsBroken.value = s.isCommsBroken
  hasFlagSeen.value = s.hasFlagSeen
}

const useInventory = () => ({
  fuel: readonly(fuel),
  ore: readonly(ore),
  metal: readonly(metal),
  parts: readonly(parts),
  hasFlagSeen: readonly(hasFlagSeen),
  energy: readonly(energy),
  isSolarCellBroken: readonly(isSolarCellBroken),
  isCommsBroken: readonly(isCommsBroken),
  setFlagSeen: (v: boolean) => {
    hasFlagSeen.value = v
  },
  addOre,
  consumeOre,
  addMetal,
  consumeMetal,
  addParts,
  consumeParts,
  drainFuel,
  refillFuel,
  hasFuel,
  tickEnergy,
  breakSolarCell,
  repairSolarCell,
  breakComms,
  repairComms,
  snapshotInventory,
  restoreInventory
})

export default useInventory
